module.exports = [
  "Você é o melhor!"
  , "Acredite em você, vai chegar bem longe!"
  , "Se consegue ver essa mensagem, quer dizer que conseguiu fazer funcionar, já pode celebrar!"
  , "Você é capaz."
  , "Isso é difícil, mas você consegue fazer isso!"
  , "Não se preocupe, ninguém sabe o que está fazendo mesmo."
  , "Tudo bem precisar de uma pausa, todos precisam de uma."
  , "Você consegue!"
  , "Uau, você é bom nisso."
  , "Existes diversas formas de resolver um problema, você só precisa de uma."
  , "Não consigi acreditar no que eu estou vendo, você é incrível!"
  , "Tenho certeza que você é um ser humano maravilhoso."
  , "Impressionante!!!"
  , "Não tenha medo de fazer perguntas!"
  , "A melhor maneira de aprender é fazendo... e você está fazendo isso maravilhosamente."
  , "Você terminou um problema mega difícil e aprendeu algo com isso, não é ótimo?"
  , "OK, lá vamos nós!!"
  , "Wow, você é uma pessoa maravilhosa!"
  , "Você é o melhor! Você pode fazer qualquer coisa!"
  , "Você tem 99 problemas mas node não é um."
  , "Hakuna Matata!"
  , "Reinicie sua vida, todos os dias."
  , "Tenha coragem!"
  , "Carpe Diem, baby!"
  , "Você é super maneiro!"
  , "Não tenha medo das mudanças!"
  , "Peça ajuda sempre que precisar."
  , "Não deixe para amanhã o que você pode comer hoje."
  , "Comece e recomece sempre que sentir necessidade."
  , "Inspira, respira, não pira!"
  , "Recomece qauntas vezes quiser!"
  , "Quanto mais a gente agradece, mais coisas boas acontecem!"
  , "Bora tentar de novo?!"
  , "Mais uma vez, você consegue!"
  , "Você consegue!"
  , "Olha que pessoa maravilhosa você é!"
  , "Você pode qualquer coisa!"
  , "Você é vitorioso!"
];